[windows]
# IP asignada al nodo de Windows 11 (Sucursal Cúcuta)
192.168.200.120

[windows:vars]
# Parámetros de autenticación y conexión remota por WinRM
ansible_user="UsuarioWindows"
ansible_password="ClaveWindows"
ansible_connection=winrm
ansible_winrm_transport=basic
ansible_winrm_scheme=http
ansible_port=5985
